{
 "title": "Control Panel",
 "description": "Centralized control panel to help teams to drill down and access metrics, traces and logs between systems.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"^$Node$\"}, pod)"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$Pod\", node=\"$Node\"}, pod_ip)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$Pod\"}, container)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$Pod\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"user|system\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes))/1024/1024/1024",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})/1024/1024/1024",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})/1024/1024/1024",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})/1024/1024/1024",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Disk (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"})/1024/1024/1024",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\"})/1024/1024/1024",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Pod (Instances Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum({__name__=~\"kubelet_running_pod_count|kubelet_running_pods\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  { "title": "Node Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cpu (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{kubernetes_node=\"$Node\",mode=~\"user|system\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$Node\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "count(node_cpu_seconds_total{kubernetes_node=\"$Node\", mode=\"system\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$Node\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum (node_memory_MemTotal_bytes{kubernetes_node=\"$Node\"} - (node_memory_MemFree_bytes{kubernetes_node=\"$Node\"} + node_memory_Buffers_bytes{kubernetes_node=\"$Node\"} + node_memory_Cached_bytes{kubernetes_node=\"$Node\"}))/1024/1024/1024",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$Node\", resource=\"memory\"})/1024/1024/1024",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=\"$Node\",resource=\"memory\"})/1024/1024/1024",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$Node\", resource=\"memory\"})/1024/1024/1024",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Disk (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_node=\"$Node\",mountpoint=\"/\"} - node_filesystem_avail_bytes{kubernetes_node=\"$Node\",mountpoint=\"/\"})/1024/1024/1024",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_node=\"$Node\",mountpoint=\"/\"})/1024/1024/1024",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Network Traffic (KBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{kubernetes_node=\"$Node\",device=\"eth0\"}[5m])/1024",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{kubernetes_node=\"$Node\",device=\"eth0\"}[5m])/1024",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "title": "Pod Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cpu (mCores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod=\"$Pod\",namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=\"$Pod\",resource=\"cpu\",namespace=\"$Namespace\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=\"$Pod\",resource=\"cpu\",namespace=\"$Namespace\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod=\"$Pod\",namespace=\"$Namespace\"})/1024/1024",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=\"$Pod\",resource=\"memory\",namespace=\"$Namespace\"})/1024/1024",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=\"$Pod\",resource=\"memory\",namespace=\"$Namespace\"})/1024/1024",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Disk (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container!=\"POD\",container!=\"\",pod=\"$Pod\",namespace=\"$Namespace\"})/1024/1024",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Network Traffic (KBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$Pod\",namespace=\"$Namespace\"}[5m]))/1024",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$Pod\",namespace=\"$Namespace\"}[5m]))/1024",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Container Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  }
 ]
}